<?php
/**
 * @file
 * This module provides a block plugin with a simple jQuery countdown timers
 *
 * Author: Sebastjan Tavčar
 */
use Drupal\block\Entity\Block;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Access\AccessResult;

function event_timers_block_access(Block $block, $operation, AccountInterface $account)
{
    
    if ($operation == 'view') {
        if ($block->id() == 'countdowntimer') {
            $roles = \Drupal::currentUser()->getRoles();
            
            //Now based on Node Pages, Hide the block
            $node = \Drupal::routeMatch()->getParameter('node');
            if (!$node || (($node instanceof \Drupal\node\NodeInterface) && ($node->gettype() != 'event'))) {
                //Hiding the block if the node is not 'event' type
                return AccessResult::forbiddenIf(true)->addCacheableDependency($block);
            }
            
        }
    }
}
